name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          
      - name: Install Ruff
        run: pip install ruff
        
      - name: Run Ruff Format
        run: ruff format .
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Style: Format code with Ruff"